### ISSUE TITLE
Darkmode is not working

### ISSUE THREAD

**Issue by PLMBakery** [PLMBakery/LiNotium#21]
during test found that dark mode ist not working

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\z004rxsw\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "G:\My Drive\Gitea\LiNotium\app\menu_manager.py", line 25, in <lambda>
    theme_menu.add_command(label="Dark Mode", command=lambda: set_theme("dark", root, style))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\My Drive\Gitea\LiNotium\app\theme_manager.py", line 16, in set_theme
    widget.config(bg="black", fg="white", insertbackground='white')
  File "C:\Users\z004rxsw\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1702, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z004rxsw\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1692, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-fg"

**Comment by PLMBakery** [comment]
still not working, can´t find the issue yet
